use_frameworks!

target 'TestPod_Example' do
  pod 'TestPod', :path => '../'

  target 'TestPod_Tests' do
    inherit! :search_paths
      pod 'SDWebImage'
      pod 'YYKit'
      pod 'XSCommunityLib',:svn =>'http://svn.91sph.com/svn/ios/subassembly/XSCommunity',:tag =>'2.0.0'
  end
end
